name: Deploy to Render
on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build Backend
        run: |
          cd backend
          mvn clean package -DskipTests
          ls -la target/
      - uses: actions/upload-artifact@v4
        with:
          name: backend-jar
          path: backend/target/*.jar

      - name: Build Frontend
        run: |
          cd frontend
          npm install
          npm run build
          ls -la build/  # Проверка
      - uses: actions/upload-artifact@v4
        with:
          name: frontend-build
          path: frontend/build/

      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Prepare Files
        run: |
          mkdir -p backend/target frontend/build
          cp artifacts/backend-jar/*.jar backend/target/
          cp -r artifacts/frontend-build/* frontend/build/

      - name: Deploy to Render
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
          BACKEND_SERVICE_ID: ${{ secrets.BACKEND_SERVICE_ID }}
          FRONTEND_SERVICE_ID: ${{ secrets.FRONTEND_SERVICE_ID }}
        run: |
          curl -X POST \
            -H "Authorization: Bearer $RENDER_API_KEY" \
            -H "Accept: application/json" \
            "https://api.render.com/v1/services/$BACKEND_SERVICE_ID/deploys"
          curl -X POST \
            -H "Authorization: Bearer $RENDER_API_KEY" \
            -H "Accept: application/json" \
            "https://api.render.com/v1/services/$FRONTEND_SERVICE_ID/deploys"
